import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import { fontSans } from '@/config/fonts';
import clsx from 'clsx';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string }; // Получаем локаль через параметры
}) {
  return (
    <html lang={params.locale || 'en'}>
      <body
        className={clsx('font-sans antialiased dark:bg-[#121212]', fontSans.className)}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
